version: '3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  listener:
    build: entry_point
    volumes:
      - ./entry_point:/entry_point
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build: api
    volumes:
      - ./api:/api:z
    ports:
      - 80:80
  
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WHITELIST=
    volumes:
      - ./transmission/config:/config:z
      - ./transmission/downloads:/downloads:z
      - ./transmission/watch:/watch:z
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped